version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps # Start from the dependencies stage (lightweight)
    container_name: portfolio-dev
    volumes:
      - .:/app # Sync local folder with container to see changes
      - /app/node_modules # Prevent local node_modules from conflicting/overwriting container's if needed, though they match here.
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev # Start in dev mode instead of prod
